INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_TRAFFIC_GENERATOR traffic_generator)

FIND_PATH(
    TRAFFIC_GENERATOR_INCLUDE_DIRS
    NAMES traffic_generator/api.h
    HINTS $ENV{TRAFFIC_GENERATOR_DIR}/include
        ${PC_TRAFFIC_GENERATOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    TRAFFIC_GENERATOR_LIBRARIES
    NAMES gnuradio-traffic_generator
    HINTS $ENV{TRAFFIC_GENERATOR_DIR}/lib
        ${PC_TRAFFIC_GENERATOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TRAFFIC_GENERATOR DEFAULT_MSG TRAFFIC_GENERATOR_LIBRARIES TRAFFIC_GENERATOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(TRAFFIC_GENERATOR_LIBRARIES TRAFFIC_GENERATOR_INCLUDE_DIRS)

